package io.github.sgrishchenko.karakum.nodeModulesNamespace

import io.github.sgrishchenko.karakum.configuration.InputResolutionStrategy
import io.github.sgrishchenko.karakum.configuration.plain
import io.github.sgrishchenko.karakum.generate
import io.github.sgrishchenko.karakum.loadTestConfig
import io.github.sgrishchenko.karakum.util.ruleOf
import kotlinx.coroutines.test.runTest
import node.buffer.BufferEncoding
import node.buffer.utf8
import node.fs.*
import node.path.path
import kotlin.test.Test
import kotlin.test.assertTrue
import kotlin.test.assertFalse

class NodeModulesNamespaceTest {
    @Test
    fun test() = runTest {
        val testConfig = loadTestConfig()
        val cwd = path.resolve(testConfig.lib, "kotlin", "nodeModulesNamespace")
        val outputDir = path.resolve(testConfig.output, "nodeModulesNamespace")

        generate {
            this.cwd = cwd
            inputResolutionStrategy = InputResolutionStrategy.plain
            input = listOf("app/**/*.d.ts")
            output = outputDir
            libraryName = "sandbox-nodeModulesNamespace"
            libraryNameOutputPrefix = false
            isolatedOutputPackage = true
            moduleNameMapper = mapOf()
            importMapper = mapOf(
                "^sandbox-vmoji$" to ruleOf("sandbox.vmoji"),
            )
        }

        val configKt = path.join(outputDir, "Config", "Config.kt")
        assertTrue(existsSync(configKt), "Expected file $configKt to exist")

        val content = readFile(configKt, BufferEncoding.utf8).replace("\r\n", "\n")

        // Namespace members from node_modules should NOT be imported individually
        // (e.g. "import sandbox.vmoji.AnimojiVersion" is wrong because that package
        // isn't generated by karakum). Instead, the namespace is accessed via
        // QualifiedName (Vmoji.AnimojiVersion) and the namespace import is handled
        // separately through the generated namespace object.
        assertFalse(
            "import sandbox.vmoji.AnimojiVersion" in content,
            "Namespace member should NOT be imported individually, but found in:\n$content"
        )

        // Also check VmojiOptions (Partial<typeof Vmoji>): property walking for
        // namespace types must be skipped to avoid dead imports of namespace members.
        val vmojiOptionsKt = path.join(outputDir, "VmojiOptions", "VmojiOptions.kt")
        assertTrue(existsSync(vmojiOptionsKt), "Expected file $vmojiOptionsKt to exist")

        val vmojiOptionsContent = readFile(vmojiOptionsKt, BufferEncoding.utf8).replace("\r\n", "\n")
        assertFalse(
            "import sandbox.vmoji" in vmojiOptionsContent,
            "Namespace type property walking should NOT produce individual member imports, but found in:\n$vmojiOptionsContent"
        )
        // Namespace import (import type * as X) from node_modules resolves to
        // a synthetic module namespace (SourceFile declaration), not a real
        // namespace object. Since the module is mapped to a single package via
        // importMapper, the QualifiedName is flattened: Vmoji.AnimojiVersion
        // becomes just AnimojiVersion with a direct import.
        val namespaceImportKt = path.join(outputDir, "NamespaceImport", "NamespaceImportConfig.kt")
        assertTrue(existsSync(namespaceImportKt), "Expected file $namespaceImportKt to exist")

        val namespaceImportContent = readFile(namespaceImportKt, BufferEncoding.utf8).replace("\r\n", "\n")
        assertFalse(
            "import sandbox.vmoji.Vmoji" in namespaceImportContent,
            "Synthetic module namespace should NOT be imported as namespace object, but found in:\n$namespaceImportContent"
        )
        assertTrue(
            "import sandbox.vmoji.AnimojiVersion" in namespaceImportContent,
            "Synthetic module namespace member should be imported directly, but not found in:\n$namespaceImportContent"
        )
    }
}
